version: "3.1"

services:
  vpn:
    build:
      context: .
      args:
       - version=master
    secrets:
     - gt.key
    ports:
     - 5000:5000/udp
    cap_add:
     - NET_ADMIN
    restart: always
    command: keyfile /run/secrets/gt.key

secrets:
  gt.key:
    file: gt.key
